export const appTheme = {
  colors: {
    background: '#eef4f8',
    backgroundAlt: '#f8fbfd',
    surface: '#ffffff',
    surfaceMuted: '#f1f5f9',
    border: '#d7e0ea',
    text: '#0f172a',
    textMuted: '#5b6b7f',
    textSoft: '#7c8a9b',
    primary: '#0f766e',
    primarySoft: '#d9f3f0',
    primaryText: '#ffffff',
    secondary: '#1d4ed8',
    secondarySoft: '#dbeafe',
    warningSoft: '#fff5d6',
    warningText: '#8a5a00',
    dangerSoft: '#fee4e4',
    dangerText: '#b42318',
    successSoft: '#dcfce7',
    successText: '#166534',
  },
  radii: {
    xl: 28,
    lg: 22,
    md: 18,
    sm: 14,
    pill: 999,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
    xxl: 32,
  },
  fontFamily: 'Manrope_400Regular',
} as const;
